# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: pull prod branch
      run: |
        git fetch origin prod:prod

    - name: checkout prod and merge stable
      run: |
        git checkout prod
        git merge -X theirs stable --allow-unrelated-histories

    - run: npm i
    - run: npm ci

    - name: build static site
      run: |
        npm run build-prod --if-present

    - name: commit
      continue-on-error: true
      run: |
        # Stage the file and commit
        git add .
        git commit -m "build static site"

    - name: push
      run: |
        # Push to origin/prod
        git push origin prod
